# This docker file build a editable image.
# You could directly edit the source code at `/home/brkraw-legacy to make changes. Or you could mount your brkraw-legacy code folder to /home/brkraw-legacy

FROM python:3.11
WORKDIR /home
RUN mkdir ./brkraw-legacy
WORKDIR /home/brkraw-legacy
COPY . .
RUN python -m pip install --editable /home/brkraw-legacy
RUN mkdir /data
WORKDIR /data

CMD echo '--------------------'; \
    echo 'To use the bids converter:'; \
    echo 'first run bids_helper'; \
    echo 'brkraw-legacy bids_helper <input dir> <output filename> -j'; \
    echo 'second, run converter'; \
    echo 'brkraw-legacy bids_convert <input dir> <BIDS datasheet.csv> -j <JSON syntax template.json> -o <output dir>';\
    echo '--------------------'; \
    bash

